# Generated by Django 2.2.3 on 2019-07-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstItem', models.TextField(null=True)),
                ('secondItem', models.TextField(null=True)),
                ('thirdItem', models.TextField(null=True)),
            ],
        ),
    ]
