# Generated by Django 2.2.3 on 2019-07-05 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='today',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
